### ISSUE TITLE
error: Import 'https://deno.land/x/jpeg.ts/mod.ts' failed: 404 Not Found

### ISSUE THREAD

**Issue by viruha** [fakoua/ink#5]
the module seems to be no longer available

**Comment by fakoua** [comment]
Thank you for reporting this issue, 
It is due to deno repo change, deno repos no longer support DOT in the pack name.

Issue fixed, please try:

deno run -A -r  https://deno.land/x/ink/welcome.ts

-r for Reload.

Thanks
